version: "3.8"

services:
  postgres:
    image: cyberw/locust-timescale:6
    networks:
      - timenet
    expose:
      - 5432
    ports:
      - 0.0.0.0:5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - TIMESCALEDB_TELEMETRY=off
    volumes:
      - postgres_data:/var/lib/postgresql/data

  grafana:
    image: cyberw/locust-grafana:3
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_LOG_LEVEL=warn # reduce log spamming. Remove this if you need to debug grafana.
    ports:
      - 0.0.0.0:3000:3000
    networks:
      - timenet
    volumes:
      - grafana_data:/var/lib/grafana

networks:
  timenet: null

volumes:
  postgres_data: null
  grafana_data: null
